package com.pruebagui2.hablador;
import com.sun.speech.freetts.*;
/**
 *
 * @author Julian
 */
public class Hablador extends javax.swing.JFrame {

    /**
     * Creates new form Hablador
     */
    public Hablador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TextoParaSerOido = new javax.swing.JTextArea();
        BotonLeerTexto = new javax.swing.JButton();
        BotonBorrarTexto = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TextoParaSerOido.setColumns(20);
        TextoParaSerOido.setRows(5);
        TextoParaSerOido.setToolTipText("Escribe aquí el texto");
        jScrollPane1.setViewportView(TextoParaSerOido);

        BotonLeerTexto.setText("Leer Texto");
        BotonLeerTexto.setToolTipText("Pulsa para leer el texto del área de texto");
        BotonLeerTexto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonLeerTextoMouseClicked(evt);
            }
        });

        BotonBorrarTexto.setText("Borrar texto");
        BotonBorrarTexto.setToolTipText("Pulsa para borrar el texto del area de texto");
        BotonBorrarTexto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonBorrarTextoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BotonLeerTexto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 204, Short.MAX_VALUE)
                        .addComponent(BotonBorrarTexto)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonLeerTexto)
                    .addComponent(BotonBorrarTexto))
                .addGap(0, 12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonBorrarTextoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonBorrarTextoMouseClicked
        TextoParaSerOido.setText("");
    }//GEN-LAST:event_BotonBorrarTextoMouseClicked

    private void BotonLeerTextoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonLeerTextoMouseClicked
        String sText = TextoParaSerOido.getText();
        if(sText != null && sText.trim().length()>0){
            VoiceManager voiceManager = null;
            Voice syntheticVoice = null;
            try{
                voiceManager = VoiceManager.getInstance();
                syntheticVoice = voiceManager.getVoice("kevin");
                syntheticVoice.allocate();
                syntheticVoice.speak(sText);
            }catch(Exception e){
            e.printStackTrace();
            }finally{
            syntheticVoice.deallocate();
            }
        }
           
           
    }//GEN-LAST:event_BotonLeerTextoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Hablador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Hablador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Hablador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Hablador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Hablador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonBorrarTexto;
    private javax.swing.JButton BotonLeerTexto;
    private javax.swing.JTextArea TextoParaSerOido;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
